---

- name: Jellyfin Key
  apt_key:
    url: https://repo.jellyfin.org/debian/jellyfin_team.gpg.key
    keyring: /usr/share/keyrings/jellyfin-archive-keyring.gpg
    state: present

- name: Add Jellyfin repo
  register: jellyfin_repo
  apt_repository: repo='deb [signed-by=/usr/share/keyrings/jellyfin-archive-keyring.gpg arch=arm64] https://repo.jellyfin.org/debian bullseye main' state=present

- name: Install Jellyfin
  register: jellyfin_app
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - jellyfin
    state:  present
    update_cache: yes
  when: jellyfin_repo.changed

- name: Restart JellyFin
  ansible.builtin.service:
    name: jellyfin
    state: restarted
    enabled: yes
  when: jellyfin_app.changed