---

- name: Jellyfin Key
  apt_key:
    url: https://repo.jellyfin.org/debian/jellyfin_team.gpg.key
    keyring: /usr/share/keyrings/jellyfin-archive-keyring.gpg
    state: present

- name: add Jellyfin repo
  apt_repository: repo='deb [signed-by=/usr/share/keyrings/jellyfin-archive-keyring.gpg arch=arm64] https://repo.jellyfin.org/debian bullseye main' state=present

- name: Install Jellyfin
  apt: name=['apt-transport-https','jellyfin'] state=present update_cache=yes
  register: jellyfin_app

- name: Restart JellyFin
  ansible.builtin.service:
    name: jellyfin
    state: restart
    enabled: yes
  when: jellyfin_app.changed