---
# To verify sensor is working check below steps
# zabbix_get -s 127.0.0.1 -k dht.pull[2]
# zabbix_get -s 127.0.0.1 -k dht.pull[4]
# Download Zabbix Template for DHT sensor
# https://zabbix.tips/wp-content/uploads/2016/05/template_dht22_module.zip
# Update Insert "Adafruit DHT parameters to Zabbix-Agent" as per the sensor tyep and pin no.

# - name: Install zabbix-agent
#   ansible.builtin.apt:
#     update_cache: yes
#     name: 
#       - zabbix-agent
#       - zabbix-proxy-sqlite3
#     state: latest

# - name: Install DHT dependecies (Python 3* and git)
#   ansible.builtin.apt:
#     update_cache: yes
#     name: 
#       - git
#       - python3
#       - python3-dev
#       - python3-apt
#       - python3-setuptools

# - name: Change default to python3
#   ansible.builtin.command: update-alternatives --install /usr/bin/python python /usr/bin/python3 10

# - name: Clone Adafruit DHT repo
#   ansible.builtin.git:
#     repo: https://github.com/adafruit/Adafruit_Python_DHT.git
#     dest: /srv/Adafruit_Python_DHT

# - name: Run Adafruit DHT python script
#   ansible.builtin.command: python3 /srv/Adafruit_Python_DHT/setup.py install


# - name: Run Adafruit DHT python script
#   ansible.builtin.script: /srv/Adafruit_Python_DHT/setup.py install
#   args:
#     executable: python3

# - name: Insert Adafruit DHT parameters to Zabbix-Agent
#   ansible.builtin.lineinfile:
#     path: /etc/zabbix/zabbix_agentd.conf
#     line: UserParameter=dht.pull[*],sudo python3 /srv/Adafruit_Python_DHT/AdafruitDHT.py 11 24 | awk -F[=*%] '{print $$$1}'
#   state: present

# - name: Enable & Start zabbix-agent service
#   service:
#     name: zabbix-agent
#     enabled: true
#     state: restarted