---

- name: Install Docker
  register: docker_app
  apt:
    update_cache: yes
    name: 
      - docker
      - containerd
      - docker-compose
    state: latest

- name: Whoami for user to add Docker group
  command: whoami
  register: whoami-rpi
- name: Add user to Docker group
  become: true
  user:
    name: '{{ whoami-rpi }}'
    groups: docker
    append: yes
  when: docker_app.changed
  register: docker_group

- name: Enable & Start Docker service
  become: true
  service:
    name: docker
    enabled: true
    state: started
  when: docker_group.changed